import React from 'react'
import Cards from '../../components/cards/Cards'
import { FeaturesData } from './data';
import svgFeature from "../../assets/images/Group.svg"
import svgStats from "../../assets/images/statsCard.svg"
import svgSearchCard from "../../assets/images/svgSearchCard.svg"
import { Link } from 'react-router-dom';
interface Props {

}
const Features: React.FC<Props> = ({ }) => {



    return (
        <>
            <h1 className="heading font-sora font-bold text-5xl mt-20 mb-20" >Features</h1>
            <section className="w-full md:w-full lg:w-5/6">
                <ul className="w-full grid grid-cols-1 gap-12 md:grid-cols-1 md:grid-cols-2 lg:grid-cols-2">
                    {FeaturesData.map((card, index) => (
                        <Cards key={index} cardTitle={card.title} cardDescription={card.description} svg={card.svg} />
                    ))}
                </ul>
            </section>
            <h1 className="heading font-sora font-bold text-5xl mt-20 mb-20" >How does it work?</h1>
            <section className="w-full md:w-4/6 flex items-center flex-col">
                <div className="flex  flex-col md:flex-row w-full items-center items-center justify-between md:space-x-10">
                    <img src={svgFeature} alt="" height="200px" width="450px" />
                    <div className="flex  flex-col md:ml-50">
                        <h1 className="heading font-sora font-bold text-4xl mb-5 mt-20 md:mt-10 md:mt-0" >Customized Quizzes</h1>
                        <p className="w-full md:w-5/6">Pathsala reccomends questions after an intial assesment of your knowledge on the topic. We provide questions that are tailored to you to help you succed in your upcomming exams.</p>
                    </div>
                </div>
            </section>
            <section className="w-full md:w-4/6 flex items-center flex-col mt-10">
                <div className="flex  flex-col w-full items-center justify-between md:space-x-20 md:flex-row-reverse">
                    <img src={svgStats} alt="" height="200px" width="450px" />
                    <div className="flex flex-col  md:ml-50">
                        <h1 className="heading font-sora font-bold text-4xl mb-5 mt-20 md:mt-10 md:mt-0" >Personalized Stats</h1>
                        <p className="w-full md:w-5/6">Keep track of all your assignments and quzzies with our powerful suite of tools and analytics.</p>
                    </div>
                </div>
            </section>
            <section className="w-full md:w-4/6 flex items-center flex-col mt-10">
                <div className="flex  flex-col md:flex-row w-full items-center justify-between md:space-x-20">
                    <img src={svgSearchCard} alt="" height="200px" width="450px" />
                    <div className="flex flex-col md:ml-50">
                        <h1 className="heading font-sora font-bold text-4xl mb-5 mt-20 md:mt-10 md:mt-0" >Hundreds of Question Sets</h1>
                        <p className="w-full md:w-5/6">Pathsala has over 1000 questions on different topics. You can also search for flash cards or question sets generated by our users.</p>
                    </div>
                </div>
            </section>
            <section className="w-full md:w-4/6 rounded-2xl flex flex-col md:flex-row bg-blue-800 items-start p-10 flex-row mt-40 h-auto mb-20 justify-between space-y-10 md:space-y-0 ">
                <div className="flex items-start md:items-center flex-col font-sora space-y-5">
                    <p className="font-medium text-xl" style={{ opacity: "0.86" }}>PATHASALA</p>
                    <h1 className="heading font-sora font-bold text-4xl mb-5 mt-20 md:mt-10 md:mt-0">Your ultimate study partner!</h1>
                </div>
                <Link to ="/login" className="bg-darkerBlue font-sora mt-2 text-xl rounded-xl p-4 outline-none focus:outline-none font-medium">
                    Start Learning!
                </Link>
                
            </section>
        </>
    );
}
export default Features;